version: '3.9'
services:
  blog:
    container_name: blog-backend
    image: blog
    build: ./blog
    restart: unless-stopped
    volumes:
      - ./Blog:/Blog # 自动同步
    env_file:
      - .env
    ports:
      - 80:8080
    networks:
      - blog-network
    # depends_on:
    #   - mysql
  mysql:
    container_name: blog-mysql
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - blog-mysql:/var/lib/mysql
    env_file:
      - .env
    networks:
      - blog-network

volumes:
  blog-mysql:


networks:
  blog-network:
    name: blog-network
